#!/bin/sh

set -o errexit

if [ ! -f i-am-a-big-thing ]; then
    echo "You are about to be tracking head"
    echo "Make sure you are not about to lose commits on untracked branches"
    echo "Hit c to continue"
    read foo
else
    foo="c"
fi

if [ "$foo" != "c" ]; then
    echo "Bailing"
    exit -1
fi

git fetch
git stash save
git checkout master
git rebase origin/master
git submodule foreach git fetch
git submodule foreach git stash save
git submodule foreach git checkout master
git submodule foreach git rebase origin/master

exit 0
