#!/bin/sh
set -o errexit

scriptPath=$(cd ${0%/*} && pwd -P)
cd $scriptPath/..

if [ ! -f .disable-warning ]; then
    echo "You are about to be tracking head"
    echo "Make sure you are not about to lose commits on untracked branches"
    echo "Hit c to continue"
    read foo
else
    foo="c"
fi

if [ "$foo" != "c" ]; then
    echo "Bailing"
    exit -1
fi

#make sure git submodule is operating on fresh base
git fetch
git stash save
git checkout master
git rebase origin/master

git submodule init
git submodule update

git submodule foreach git fetch
git submodule foreach git stash save
git submodule foreach git checkout master
git submodule foreach git rebase origin/master

exit 0
